export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const GET_ORDER_FROM_SERVER = 'GET_ORDER_FROM_SERVER';
